### ISSUE TITLE
Self installer py should be updated for Python 3.11.2

### ISSUE THREAD

**Issue by arvindin** [gammazero/pymakeself#11]
Python Version: 3.11.2

base64.decodestring() is deprecated, it should be replaced with base64.decodebytes

**Comment by d33pster** [comment]
Hey,
if you don't have encryption needs, try warlocksfx (made if for my own project).
supports python 3.9+
GitHub: https://github.com/d33pster/warlockSFX

**Comment by gammazero** [comment]
Fixed by #9
