### ISSUE TITLE
How about setup automation?

### ISSUE THREAD

**Issue by SzykCech4** [gammazero/pymakeself#6]
Hello!
I am interested with pymakeself in order to make my custom application installer system (at least for Linux and at best portable). I read https://pypi.org/project/pymakeself/ descritpion, but I notice there is no mention about pass command line arguments in to user setup script. If it is true - then it is huge disadvantage, because such installer can not be used by admins. This eventualy cause big bussines impact because corporation and schools nor clerks will be not interested with such cumbersome soft!
Can you explain your point of view for such issue?

**Comment by gammazero** [comment]
Clearly this is needed, and simply had not been added yet.  I will create a PR to add this functionality.

**Comment by gammazero** [comment]
This should be fixed by #7 (merged).  Please close issue if it has everything you need.
